Why does the following code...

def execute(block)
  block.call
end

execute { puts "Hello from inside the execute method!" }

Give us the following error when we run it?

block.rb1:in `execute': wrong number of arguments (0 for 1) (ArgumentError)
from test.rb:5:in `<main>'

Answer:
Because the definition of the execute method requires a single standard variable but instead it recieved a whole method call with it's own argument (puts "Hello..."). If we want 'block' to accept an actual block we need to demonstrate that using the ampersand sign: '&block'.